apiVersion: v1
kind: Service
metadata:
  labels:
    apps: quizo
  name: quizo
spec:
  type: NodePort
  selector:
    app: quizo
  ports:
    - name: quizo
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizo
  template:
    metadata:
      labels:
        app: quizo
    spec:
      containers:
        - name: quizo
          image: quizo:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
