apiVersion: v1
kind: Service
metadata:
  labels:
    apps: answero
  name: answero
spec:
  type: NodePort
  selector:
    app: answero
  ports:
    - name: answero
      port: 9090
      targetPort: 9090
      nodePort: 30070

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: answero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answero
  template:
    metadata:
      labels:
        app: answero
    spec:
      containers:
        - name: answero
          image: answero:v1
          ports:
            - containerPort: 9090
          imagePullPolicy: IfNotPresent
